### ISSUE TITLE
Simplify computing force of gravity

### ISSUE THREAD

**Issue by ffflick-gh** [FFFiend/PyJac-Coin-Drop#1]
Currently, the system for computing gravitational force is fairly complicated with like three different constants involved. Right now, it uses Newton's formula for force due to gravity, `F = G * (Mm)/(r^2)`. This has the nice property where the gravity increases the closer the attracted object is to the attracting object (and can be seen in the simulation too if you squint your eyes a bit!). However, besides just being complicated, it's also not *too* realistic. We mostly experience the same 9.8 m/s^2 at the surface. For our simulation too, we'll choose an appropriate constant force and use that, which should also simplify things a bit.

**Comment by FFFiend** [comment]
donezo!
