### ISSUE TITLE
Make air particles respect `AIR_BOUNDARY`

### ISSUE THREAD

**Issue by ffflick-gh** [FFFiend/PyJac-Coin-Drop#3]
We don't plan to implement collision between air particles and the pond. Instead, we'll limit the air particles' movement to a container whose bottom wall is slightly above the pond. The `y` value for this boundary is given by `AIR_BOUNDARY`. Make it so that air particles collide with this boundary instead of the bottom of the canvas.

**Comment by FFFiend** [comment]
DONE AND DUSTED!!
